export const INITIAL_VEHICLES = [
  {
    id: 'bicycle',
    name: 'Bicycle',
    emoji: '🚲',
    iconName: 'bicycle-outline',
    iconType: 'Ionicons',
    category: 'Eco Mobility',
    subtext: 'Short-range eco logistics',
    speed: '15 km/h',
    badge: 'Zero Emission',
  },
  {
    id: 'two_wheeler',
    name: 'Two-wheeler',
    emoji: '🛵',
    iconName: 'moped-outline',
    iconType: 'MaterialCommunityIcons',
    category: 'Express Transit',
    subtext: 'Fast urban & rural courier',
    speed: '45 km/h',
    badge: 'Rapid Agile',
  },
  {
    id: 'car',
    name: 'Car',
    emoji: '🚗',
    iconName: 'car-sport-outline',
    iconType: 'Ionicons',
    category: 'Passenger & Cargo',
    subtext: 'All-weather regional mobility',
    speed: '70 km/h',
    badge: 'All Terrain',
  },
  {
    id: 'truck',
    name: 'Truck',
    emoji: '🚚',
    iconName: 'truck-outline',
    iconType: 'MaterialCommunityIcons',
    category: 'Heavy Freight',
    subtext: 'High-payload NER supply lines',
    speed: '55 km/h',
    badge: 'Heavy Cargo',
  },
];

export const EXTRA_VEHICLE_OPTIONS = [
  {
    id: 'bus',
    name: 'Bus',
    emoji: '🚌',
    iconName: 'bus-outline',
    iconType: 'Ionicons',
    category: 'Mass Transit',
    subtext: 'Inter-district public transit',
    speed: '50 km/h',
    badge: 'Mass Transit',
  },
  {
    id: 'van',
    name: 'Van',
    emoji: '🚐',
    iconName: 'van-passenger',
    iconType: 'MaterialCommunityIcons',
    category: 'Commercial',
    subtext: 'Mid-sized freight carrier',
    speed: '65 km/h',
    badge: 'Mid Capacity',
  },
  {
    id: 'ambulance',
    name: 'Ambulance',
    emoji: '🚑',
    iconName: 'ambulance',
    iconType: 'FontAwesome5',
    category: 'Critical Care',
    subtext: 'Priority medical corridor',
    speed: '85 km/h',
    badge: 'Priority SOS',
  },
  {
    id: 'delivery_vehicle',
    name: 'Delivery Vehicle',
    emoji: '📦',
    iconName: 'truck-delivery-outline',
    iconType: 'MaterialCommunityIcons',
    category: 'Logistics',
    subtext: 'E-commerce & supply link',
    speed: '60 km/h',
    badge: 'Last-Mile',
  },
  {
    id: 'tractor',
    name: 'Tractor',
    emoji: '🚜',
    iconName: 'tractor',
    iconType: 'MaterialCommunityIcons',
    category: 'Agri-Tech',
    subtext: 'Rural & hill farm logistics',
    speed: '30 km/h',
    badge: 'Hill Terrain',
  },
  {
    id: 'emergency_vehicle',
    name: 'Emergency Vehicle',
    emoji: '🚨',
    iconName: 'shield-alert-outline',
    iconType: 'MaterialCommunityIcons',
    category: 'Disaster Relief',
    subtext: 'Disaster & rescue response',
    speed: '80 km/h',
    badge: 'Emergency',
  },
];
